### ISSUE TITLE
about dataset 

### ISSUE THREAD

**Issue by wangsen1994** [lxf8519/DL-hybrid-precoder#1]
when i use deepMIMO to generator data，it just generators the channel vetor， how to generator the channel matrix, and in your paper you empty 64 antenns with 3 RFchains for both mobile users and base station, but in deepMIMO generator matlab code i don't know how to implement it

**Comment by BZDJSM353** [comment]
> 当我使用deepMIMO生成数据时，它仅生成信道向量，如何生成信道矩阵，并且在您的论文中，您为移动用户和基站清空了具有3个RF链的64个天线，但是在deepMIMO生成器中，我不这样做不知道如何实施



> when i use deepMIMO to generator data，it just generators the channel vetor， how to generator the channel matrix, and in your paper you empty 64 antenns with 3 RFchains for both mobile users and base station, but in deepMIMO generator matlab code i don't know how to implement it

Do you know which folder or how to run "python main_train_beamform .py -train 1"? I really don't know how to find it.

**Comment by lxf8519** [comment]
> when i use deepMIMO to generator data，it just generators the channel vetor， how to generator the channel matrix, and in your paper you empty 64 antenns with 3 RFchains for both mobile users and base station, but in deepMIMO generator matlab code i don't know how to implement it

For this question, yes, the deepMIMO generator only give you the channel vectors. However, in this paper, the best precoding vectors are also needed as labels. There are two ways to get the labels, either of them is OK:
1. Download the dataset provided in the Dataset section in the instruction of the code (mat files from google drive). It is not the Matlab code from deepMIMO website.
2. Given the channel vectors, use some algorithms which can be found in many reference papers to calculate the precoding vectors for the channels. You need to write your own code for the algorithm.

**Comment by lxf8519** [comment]
> Do you know which folder or how to run "python main_train_beamform .py -train 1"? I really don't know how to find it.

The file main_train_beamform .py is in the root folder. You can run it in this folder. You also need to download the dataset (mat files) from the link in the Dataset section and copy it to MIMO_dataset folder.

**Comment by BZDJSM353** [comment]
Thank you very much for your answer. I will download the data set. I will try again.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lxf8519"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 中午1:03
收件人:&nbsp;"lxf8519/DL-hybrid-precoder"<DL-hybrid-precoder@noreply.github.com&gt;;
抄送:&nbsp;"。。。"<3061057942@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lxf8519/DL-hybrid-precoder] about dataset  (#1)





  
Do you know which folder or how to run "python main_train_beamform .py -train 1"? I really don't know how to find it.
  
The file main_train_beamform .py is in the root folder. You can run it in this folder. You also need to download the dataset (mat files) from the link in the Dataset section and copy it to MIMO_dataset folder.

**Comment by hsssss1** [comment]
When I run the code, I get the following error message."ValueError: None values not supported."But when I use the pre-trained model in save_model for testing，it can produce results. I don't know where the problem is，Do you know how to cause this situation?（version is Tensorflow 1.13.1, Keras 2.3.1）The following is the complete error message，looking forward to your answer and thank you.

`File "D:/R/DL-hybrid-precoder-master/DL-hybrid-precoder-master/main_train/main_train_beamforming.py", line 52, in <module>
    precoder.train(10*h_train.data, h_train.labels, 10*h_test.data, h_test.labels, epochs, batch_size)
  File "D:\R\DL-hybrid-precoder-master\DL-hybrid-precoder-master\main_train\Model\network_base.py", line 20, in train
    callbacks=callbacks)
  File "C:\Users\admin\Anaconda3\lib\site-packages\keras\engine\training.py", line 1213, in fit
    self._make_train_function()
  File "C:\Users\admin\Anaconda3\lib\site-packages\keras\engine\training.py", line 316, in _make_train_function
    loss=self.total_loss)
  File "C:\Users\admin\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\keras\optimizers.py", line 543, in get_updates
    p_t = p - lr_t * m_t / (K.sqrt(v_t) + self.epsilon)
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 815, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\admin\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 454, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.`

**Comment by hsssss1** [comment]
> > when i use deepMIMO to generator data，it just generators the channel vetor， how to generator the channel matrix, and in your paper you empty 64 antenns with 3 RFchains for both mobile users and base station, but in deepMIMO generator matlab code i don't know how to implement it
> 
> For this question, yes, the deepMIMO generator only give you the channel vectors. However, in this paper, the best precoding vectors are also needed as labels. There are two ways to get the labels, either of them is OK:
> 
> 1. Download the dataset provided in the Dataset section in the instruction of the code (mat files from google drive). It is not the Matlab code from deepMIMO website.
> 2. Given the channel vectors, use some algorithms which can be found in many reference papers to calculate the precoding vectors for the channels. You need to write your own code for the algorithm.

How did you generate the  precoding vectors as labels in this paper？
Could you share the algorithms and code which you used to calculate the precoding vectors for the channels ?I will be very grateful for you.
